// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKWwNEGkKzAHWm0HfaH3Ecreyy3CaOWe4',
    appId: '1:243696280805:web:e29df5477cdbdd859ea00c',
    messagingSenderId: '243696280805',
    projectId: 'inspire-blog-app',
    authDomain: 'inspire-blog-app.firebaseapp.com',
    storageBucket: 'inspire-blog-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAY8stSoYQA9OpY3eiFUp-aL9Ag1hNN8',
    appId: '1:243696280805:android:f5b1a69d8f3d831c9ea00c',
    messagingSenderId: '243696280805',
    projectId: 'inspire-blog-app',
    storageBucket: 'inspire-blog-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NYaQ7EqiGKosZ_igl44eTYfQu0x9Vrs',
    appId: '1:243696280805:ios:c51901df2155eb559ea00c',
    messagingSenderId: '243696280805',
    projectId: 'inspire-blog-app',
    storageBucket: 'inspire-blog-app.appspot.com',
    iosClientId: '243696280805-t2q9gugpb1j46cs31lumro1i5rv7tr3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NYaQ7EqiGKosZ_igl44eTYfQu0x9Vrs',
    appId: '1:243696280805:ios:c51901df2155eb559ea00c',
    messagingSenderId: '243696280805',
    projectId: 'inspire-blog-app',
    storageBucket: 'inspire-blog-app.appspot.com',
    iosClientId: '243696280805-t2q9gugpb1j46cs31lumro1i5rv7tr3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
